// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prueba_Innovation.Models;

namespace Prueba_Innovation.Migrations
{
    [DbContext(typeof(InnovationContext))]
    partial class InnovationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Prueba_Innovation.Models.Conductor", b =>
                {
                    b.Property<string>("DNI")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Puntos")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DNI");

                    b.HasIndex("DNI")
                        .IsUnique();

                    b.ToTable("Conductores");
                });

            modelBuilder.Entity("Prueba_Innovation.Models.Infracciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DNI_Conductor")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Matricula_Vehiculo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Puntos")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DNI_Conductor");

                    b.HasIndex("Matricula_Vehiculo");

                    b.ToTable("Infracciones");
                });

            modelBuilder.Entity("Prueba_Innovation.Models.Vehiculo", b =>
                {
                    b.Property<string>("Matricula")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DNI_Conductor")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Matricula");

                    b.HasIndex("DNI_Conductor");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("Prueba_Innovation.Models.Infracciones", b =>
                {
                    b.HasOne("Prueba_Innovation.Models.Conductor", "Conductor")
                        .WithMany()
                        .HasForeignKey("DNI_Conductor");

                    b.HasOne("Prueba_Innovation.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("Matricula_Vehiculo");
                });

            modelBuilder.Entity("Prueba_Innovation.Models.Vehiculo", b =>
                {
                    b.HasOne("Prueba_Innovation.Models.Conductor", "Conductor")
                        .WithMany()
                        .HasForeignKey("DNI_Conductor");
                });
#pragma warning restore 612, 618
        }
    }
}
